language: csharp

sudo: false  # use the new container-based Travis infrastructure 

dist: xenial
mono: latest
dotnet: 2.2

install:
  # workaround for missing .net 4.6.1 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1-api/

script: 
  - ./build.sh All
